"""init

Revision ID: db077b74c8ed
Revises: 
Create Date: 2026-02-10 00:20:45.702848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db077b74c8ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('link_url', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('boosts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('paid_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boosts_listing_id'), ['listing_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'buyer_id', 'seller_id', name='uq_conv_triplet')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_seller_id'), ['seller_id'], unique=False)

    op.create_table('listing_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_images_listing_id'), ['listing_id'], unique=False)

    op.create_table('observing',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'listing_id', name='uq_observing_user_listing')
    )
    with op.batch_alter_table('observing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observing_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observing_user_id'), ['user_id'], unique=False)

    op.create_table('safe_meet_locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('place_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Numeric(), nullable=False),
    sa.Column('lng', sa.Numeric(), nullable=False),
    sa.Column('place_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safe_meet_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safe_meet_locations_listing_id'), ['listing_id'], unique=False)

    op.create_table('safety_ack_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('ack_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safety_ack_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_ack_events_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_ack_events_user_id'), ['user_id'], unique=False)

    op.create_table('boost_impressions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('boost_id', sa.String(length=36), nullable=False),
    sa.Column('viewer_user_id', sa.String(length=36), nullable=True),
    sa.Column('shown_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['boost_id'], ['boosts.id'], ),
    sa.ForeignKeyConstraint(['viewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boost_impressions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boost_impressions_boost_id'), ['boost_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_boost_impressions_viewer_user_id'), ['viewer_user_id'], unique=False)

    op.drop_table('reports')
    op.drop_table('favorites')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('price_cents', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('zip', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('pickup_or_shipping', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('is_sold', sa.Boolean(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('listings_id_seq'::regclass)"))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               nullable=False)
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_listings_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('listings_seller_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('location_lng')
        batch_op.drop_column('image_urls')
        batch_op.drop_column('status')
        batch_op.drop_column('location_lat')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('seller_id')
        batch_op.drop_column('price')
        batch_op.drop_column('radius_km')
        batch_op.drop_column('location_name')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.String(length=36), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('messages_receiver_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('messages_listing_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'])
        batch_op.drop_column('read')
        batch_op.drop_column('listing_id')
        batch_op.drop_column('receiver_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('rating_avg', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_pro', sa.Boolean(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_column('location_lng')
        batch_op.drop_column('bio')
        batch_op.drop_column('location_lat')
        batch_op.drop_column('username')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('location_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('location_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bio', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'])
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'])
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
        batch_op.drop_column('is_pro')
        batch_op.drop_column('rating_count')
        batch_op.drop_column('rating_avg')
        batch_op.drop_column('display_name')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_listing_id_fkey'), 'listings', ['listing_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('messages_receiver_id_fkey'), 'users', ['receiver_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('sender_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('conversation_id')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('radius_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_urls', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('listings_seller_id_fkey'), 'users', ['seller_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_listings_user_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('condition',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('listings_id_seq'::regclass)"))
        batch_op.drop_column('is_sold')
        batch_op.drop_column('pickup_or_shipping')
        batch_op.drop_column('zip')
        batch_op.drop_column('city')
        batch_op.drop_column('price_cents')
        batch_op.drop_column('user_id')

    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('favorites_listing_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('favorites_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('favorites_pkey')),
    sa.UniqueConstraint('user_id', 'listing_id', name=op.f('favorites_user_id_listing_id_key'))
    )
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reporter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reported_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reported_listing_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reported_listing_id'], ['listings.id'], name=op.f('reports_reported_listing_id_fkey')),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], name=op.f('reports_reported_user_id_fkey')),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('reports_reporter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reports_pkey'))
    )
    with op.batch_alter_table('boost_impressions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boost_impressions_viewer_user_id'))
        batch_op.drop_index(batch_op.f('ix_boost_impressions_boost_id'))

    op.drop_table('boost_impressions')
    with op.batch_alter_table('safety_ack_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_ack_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_safety_ack_events_listing_id'))

    op.drop_table('safety_ack_events')
    with op.batch_alter_table('safe_meet_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safe_meet_locations_listing_id'))

    op.drop_table('safe_meet_locations')
    with op.batch_alter_table('observing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observing_user_id'))
        batch_op.drop_index(batch_op.f('ix_observing_listing_id'))

    op.drop_table('observing')
    with op.batch_alter_table('listing_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_images_listing_id'))

    op.drop_table('listing_images')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_seller_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_listing_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_buyer_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('boosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boosts_listing_id'))

    op.drop_table('boosts')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))

    op.drop_table('subscriptions')
    op.drop_table('ads')
    # ### end Alembic commands ###
